### ISSUE TITLE
[Feat] 홈화면 UI 구현

### ISSUE THREAD

**Issue by JMM00** [23-T1-CoCo/NurVo#3]
## TODO
- [x] 홈화면 UI 구현
- [x] bottom tab 연결
- [x] navigation stack 연결
- [x] 라이브러리 설치 및 사용 설정
