### ISSUE TITLE
[Feat] 학습하기 화면 구현

### ISSUE THREAD

**Issue by JMM00** [23-T1-CoCo/NurVo#4]
## TODO
- [x] 1,2,3단계 학습하기 화면 구현
- [x] text input 받기
- [ ] 음성인식 연결하기
- [ ] 문장 저장 기능
- [ ] tts 기능 연결
