### ISSUE TITLE
[Feat] 한줄학습 화면 구현

### ISSUE THREAD

**Issue by ParkHyeLim** [23-T1-CoCo/NurVo#5]
## TODO
- [x] 사용자 저장 문장 화면
- [x] 선택 문장 학습 화면
- [ ] tts 기능 연결
